site_name: Dune Docs
site_url: https://minaminao.github.io/duneanalytics
repo_url: https://github.com/minaminao/duneanalytics
site_dir: site/dune-analytics
theme:
  language: en
  name: material
  custom_dir: overrides
  logo: images/dune-icon-only.png
  favicon: images/dune-icon-only.png
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
nav:
  - ...
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
plugins:
  - search
  - awesome-pages
  - mkdocs-video
extra:
  generator: false
  alternate:
    - name: Japanese
      link: /duneanalytics
      lang: ja
    - name: English
      link: https://dune.com/docs/
      lang: en
    - name: Chinese (Simplified)
      link: https://docs.dune.com/v/chinese/
      lang: zh
  analytics:
    provider: posthog
    api_key: !ENV POSTHOG_API_KEY
    api_host: !ENV POSTHOG_API_HOST
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js